# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b910484553ca8b91dc77b4c2dabc63823a0d52175cb9d23a2d86f69fd78ee8cdfcb26f8b2ec0e28f7c87c337b77fc9951affac4d55e44ca7e388677e2c92aa4c

test:
  secret_key_base: 06b7e3ada6bc358ab3268c5c2c551d4796e00d9d7d3c981a7093fe0f55b1dbb5d5c2ec1c13a27a8cd82fdfe6239d0dad28e123b27a7a562af6741b59e6ed600a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
